name: Windows
on: [push, pull_request]

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: "3.9"
          env:
            TOXENV: windows-pinned
        - python-version: "3.10"
          env:
            TOXENV: py
        - python-version: "3.11"
          env:
            TOXENV: py
        - python-version: "3.12"
          env:
            TOXENV: py
        - python-version: "3.13"
          env:
            TOXENV: py
        - python-version: "3.13"
          env:
            TOXENV: asyncio

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -U tox
        pip install coverage codecov  # Install coverage and Codecov tools

    - name: Run tests with coverage
      env: ${{ matrix.env }}
      run: |
        tox
        coverage xml -o coverage.xml  # Generate an XML coverage report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
       files: ./coverage.xml
       flags: unittests
       token: ${{ secrets.CODECOV_TOKEN }}  # Only needed if the repo is private
       name: windows-coverage
       slug: Ronhobs/scrapy  # Explicitly specify the repository slug

