name: Upload coverage to Codecov

on:
  push:
    branches:
      - main  # Adjust to your default branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Adjust if necessary

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install pytest pytest-cov codecov

    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Make sure to add CODECOV_TOKEN in GitHub repository secrets
        files: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
